name: Run E2E Tests
on: [pull_request]
jobs:
  run-e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: bitnami/postgresql
        ports:
          - 5672:5672
        env:
          POSTGRESQL_USERNAME: desafio
          POSTGRESQL_PASSWORD: desafio
          POSTGRESQL_DATABASE: frindafrind
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - run: npm ci
      - run: npm run test:e2e
        env:
          JWT_SECRET: testing
          DATABASE_URL: "postgresql://desafio:desafio@localhost:5672/frindafrind?schema=public"